# open ai package
from openai import OpenAI 
client = OpenAI()

api_key='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'

# *plus you need to store your openai API key as an envirnoment variable, it is called 'OPENAI_API_KEY' and the OpenAI looks for it everytime a call is made*
# https://platform.openai.com/docs/quickstart?context=python SKIP TO STEP 2 AND PICK UR OS (do for all projects version)

# call, gpt output stored in var response 
response = client.chat.completions.create(
  model="gpt-4-1106-preview",

  response_format={"type": "json_object"},

  messages=[
    # role
    {"role": "system", "content": "Database Content Generator"},

    # prompt
    {"role": "user", "content": """Generate 10 default records for each of the following database tables in JSON format, without setting any relationships or generating IDs. Assume IDs will be autogenerated by the database:

    COURSE (NAME, CREDITS, LOCATION)

    FACULTY (NAME)

    HONORSAWARDS (TITLE, DESCRIPTION)

    PROFESSOR (NAME)

    SCHOLARSHIPS (AMOUNT, TYPE)

    STUDENT (NAME, DEGREE, CREDITSEARNED, CREDITSLEFT, EMAIL, PASSWORD, GPA)


    Student grade must be in percentage form: 'X%'
    Please generate the data ensuring that it is realistic and suitable for a university database, but remember not to include any IDs as they are generated by the database."""}
  ]
)


print(response.choices[0].message.content) # this is how the data is parsed in a readable manner, just printing the 'response' var gives a bunch of random shit