-- SELECT * from IBMUSER.EMP;
-- SELECT JOB from IBMUSER.EMP;
-- SELECT LASTNAME, EMPNO, PHONENO from ibmuser.emp;
-- SELECT DEPTNAME, DEPTNO from ibmuser.dept

-- SELECT FIRSTNME
-- from IBMUSER.EMP
-- WHERE JOB='MANAGER';

-- SELECT COUNT(*) from ibmuser.emp

-- SELECT DEPTNAME, COUNT(EMPNO)
--         FROM ibmuser.dept D, ibmuser.emp E
--         WHERE D. DEPTNO = E.WORKDEPT
--         GROUP BY DEPTNAME
--         ORDER BY DEPTNAME

SELECT DEPTNAME, MAX(SALARY) + MAX(BONUS) + MAX(COMM) as MAX_COMPENSATION
    from IBMUSER.EMP E, IBMUSER.DEPT D
    where D.DEPTNO = E.WORKDEPT
    GROUP BY DEPTNAME
    ORDER BY DEPTNAME;
         